# Site settings
title: Falconius
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Playing with data
baseurl: "http://mfalcon.github.io/" # the subpath of your site, e.g. /blog/
url: "http://falconius.com" # the base hostname & protocol for your site
twitter_username: falconius
github_username:  mfalcon

# Build settings
markdown: kramdown
